version: "3.9"

services:
  db:
    image: postgres:15
    container_name: uscre-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql:ro
    ports:
      - "5432:5432"

  uscre-login:
    build: .
    container_name: uscre-login
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/tmp/uscre_logs

volumes:
  db_data:
