version: "3.9"

services:
  revieu-login:
    build: .
    container_name: revieu-login
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT:-8082}:8082"
    volumes:
      - ./logs:/tmp/revieu_logs
