services:
  revieu-login:
    image: revieu-auth-service:latest
    build: .
    container_name: revieu-login
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT:-8081}:8080"
    volumes:
      - ./logs:/tmp/revieu_logs
